version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: bot
    depends_on:
      - redis
    environment:
      - TELEGRAM_TOKEN=7304660025:AAHymFUIOCZ2hmn51scyt-pwqLiB86A2Ri8
      - REDIS_HOST=redis
      - REDIS_PORT=6379